// lib
import Head from 'next/head';
import { FormProvider, useForm } from "react-hook-form";
// components
import List from "@/components/common/List";
import FormArea from "./components/FormArea";
// hooks
import { useQueryState } from "@/hooks/useQueryState";
import { useRoute } from "@/hooks/useRoute";
// other
import styles from '../../../styles/Home.module.css'

const TopView = () => {
    const router = useRoute();
    const {
        query: { page },
    } = router;
    // const [courses]: any  = useQueryState(['Courses', page]);
    const methods = useForm({ mode: "onChange" });
    

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    ゴルフ場検索
                </h1>

                <p className={styles.description}>
                    日本全国のゴルフ場を検索しよう！！
                </p>
                <FormProvider {...methods}>
                    <FormArea />
                    <List /* listData={courses} */ />
                </FormProvider>
            </main>

            <footer className={styles.footer}>
                next.js tanstack Query 練習 ゴルフ場検索
            </footer>
        </div>
    )
}

export default TopView;
